config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  devise_for :users

  resources :posts do
    resources :comments
  end

  root 'posts#home'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
    include Bootsy::Container
    belongs_to :user
    has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first, :last, :numberofid, :profession, :yearofstudy
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first
    devise_parameter_sanitizer.for(:sign_up) << :last
    devise_parameter_sanitizer.for(:sign_up) << :numberofid
    devise_parameter_sanitizer.for(:sign_up) << :profession
    devise_parameter_sanitizer.for(:sign_up) << :yearofstudy
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
       @post = Post.find(params[:post_id])
       @comment = @post.comments.create(params[:comment].permit(:comment))
       
       @comment.user_id = current_user.id if current_user
	   @comment.save

       
       if @comment.save
           redirect_to post_path(@post)
       else
           render 'new'
       end
       
    end
    
    def edit
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
    end
    
    def update
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
         
        if @comment.update(params[:comment].permit(:comment))
            redirect_to post_path(@post)
        else
            render 'edit'
        end
    end
    
    def destroy
         @post = Post.find(params[:post_id])
         @comment = @post.comments.find(params[:id])
         if current_user == @comment.user
            @comment.destroy
        end
        redirect_to post_path(@post)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show, :home]

    def index
    	@posts = Post.all.order("created_at DESC")
    end

    def home
    end

	def show

	end

	def new
	    @post = current_user.posts.build
	end

	def create
	    @post = current_user.posts.build(post_params)

	    if @post.save
	    	redirect_to @post
	    else
	    	render 'new'
	    end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

	private

	def find_post
		@post = Post.find(params[:id])
	end

	def post_params
	    params.require(:post).permit(:title, :content, :bootsy_image_gallery_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment-section">
    <p class="comment-text"><%= comment.comment %></p>
    <h4 class="comment-author">opublikowane przez <%= comment.user.first %> <%= comment.user.last %></p>
    <% if user_signed_in? %>
        <%= link_to "Edytuj", edit_post_comment_path(comment.post, comment), class:"btn btn-default" %>
        <%= link_to "Usuń", [comment.post, comment], method: :delete, data: { confirm: "Czy jesteś pewien?"}, class:"btn btn-default" %>
    <% end %>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>
    <div class="form-group">
        <%= f.input :comment, class:"form-control" %>
    </div>
    <%= f.submit "Submit", class:"btn btn-default" %>
    
<% end %>

app/views/comments/edit.html.erb
<div class="row comment-edit">
    <h1>Edit reply</h1>
    <div class="col-md-8 col-md-offset-2">
        <%= simple_form_for([@post, @comment]) do |f| %>
        <div class="form-group title">
            <%= f.input :comment, class: 'form-control' %>
        </div>
        <div class="comment-submit">
            <%= f.submit "Submit", class:"btn btn-default" %>
        </div>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "WishList", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "New post", new_post_path %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "Community", posts_path %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Community", posts_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<% end %>
<div class="jumbotron">
  <div class="container">

    <% flash.each do |name, msg| %>
  		<%= content_tag(:div, msg, class: "alert") %>
  	<% end %>

    <%= yield %>

    
  </div>
</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="form-group title">
		<%= f.label :title, class:"title-form" %><br>
		<%= f.text_field :title, class: 'form-control' %><br>
	</div>
	<div class="form-group title">
		<%= f.label :content, class:"content-form" %><br>
		<%= f.bootsy_area :content, editor_options: { image: false, alert_unsaved: false }, class:'form-control' %><br>
	</div>
	<%= f.submit "Submit", class:"btn btn-default" %>
<% end %>

app/views/posts/edit.html.erb
<div class="row edit-post">
    <h1>Edit Post</h1> 
    <div class="col-md-8 col-md-offset-2">
        <%= render 'form' %>
        <div class="cancel-edit">
            <%= link_to "Cancel", post_path, class:"btn btn-default" %>
        </div>
    </div>
</div>

app/views/posts/home.html.erb
<div class="row banner">
    <div class="col-sm-8 col-sm-offset-2">
        <h1>Fakultety SGGW</h1>
        <%= link_to "Logowanie", new_user_session_path %>
        <%= link_to "Rejestracja", new_user_registration_path %>
    </div>
</div>

app/views/posts/index.html.erb
<div class="row community-index">
    <h1>Latest posts</h1>
    <div class="col-md-8 col-md-offset-2">
        <% @posts.each do |post| %>
        <h2><%= link_to post.title, post %></h2>
        <p><%= time_ago_in_words(post.created_at) %> ago by <%= post.user.email %></p>
    <% end %>
    </div>
</div>

app/views/posts/new.html.erb
<div class="row new-post">
    <h1>Add new post</h1>
    <div class="col-md-8 col-md-offset-2">
        <%= render 'form' %>
    </div>
</div>

app/views/posts/show.html.erb
<div class="row show-post">
    <div class="col-md-8 col-md-offset-2">
        <h1><%= @post.title %></h1>
        <p><%= raw @post.content %></p>
        <% if user_signed_in? %>
            <%= link_to "edit", edit_post_path(@post), class: "btn btn-default" %>
            <%= link_to "delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-default" %>
        <% end %>
        <h3>number of comments: <%= @post.comments.count %></h2>
        <%= render @post.comments %>
        <% if user_signed_in? %>
            <h2>Reply to post</h3>
            <%= render 'comments/form' %>
        <% end %>
    </div>
</div>